export const Data = [
  {
    id: "MBR001",
    name: "Jane Doe",
    type: "member",
    contact: "jane.doe@example.com",
    plan: "Gold",
    renewalDate: "2025-08-01",
    role: "",
    status: "active",
    checkInTime: "09:00 AM",
    method: "manual",
  },
  {
    id: "MBR002",
    name: "John Smith",
    type: "member",
    contact: "john.smith@example.com",
    plan: "Silver",
    renewalDate: "2025-07-20",
    role: "",
    status: "nearly renewal",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR003",
    name: "Emily Clarke",
    type: "member",
    contact: "emilyc@example.com",
    plan: "Platinum",
    renewalDate: "2025-06-25",
    role: "",
    status: "expired",
    checkInTime: "08:30 AM",
    method: "qr scan",
  },
  {
    id: "MBR004",
    name: "Robert Jones",
    type: "member",
    contact: "robertj@example.com",
    plan: "Gold",
    renewalDate: "2025-08-10",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR005",
    name: "Sophia Lee",
    type: "member",
    contact: "sophia.lee@example.com",
    plan: "Silver",
    renewalDate: "2025-07-30",
    role: "",
    status: "active",
    checkInTime: "10:15 AM",
    method: "biometric",
  },
  {
    id: "MBR006",
    name: "Chris Evans",
    type: "member",
    contact: "chris.evans@example.com",
    plan: "Gold",
    renewalDate: "2025-08-12",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR007",
    name: "Nina Patel",
    type: "member",
    contact: "nina.p@example.com",
    plan: "Platinum",
    renewalDate: "2025-08-18",
    role: "",
    status: "nearly renewal",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR008",
    name: "Tom Hardy",
    type: "member",
    contact: "t.hardy@example.com",
    plan: "Silver",
    renewalDate: "2025-07-12",
    role: "",
    status: "expired",
    checkInTime: "07:45 AM",
    method: "manual",
  },
  {
    id: "MBR009",
    name: "Priya Sharma",
    type: "member",
    contact: "priya.s@example.com",
    plan: "Gold",
    renewalDate: "2025-08-22",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR010",
    name: "David Kim",
    type: "member",
    contact: "david.kim@example.com",
    plan: "Silver",
    renewalDate: "2025-07-28",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR011",
    name: "Lily Chen",
    type: "member",
    contact: "lily.chen@example.com",
    plan: "Platinum",
    renewalDate: "2025-07-18",
    role: "",
    status: "nearly renewal",
    checkInTime: "09:40 AM",
    method: "qr scan",
  },
  {
    id: "MBR012",
    name: "Raj Verma",
    type: "member",
    contact: "raj.verma@example.com",
    plan: "Gold",
    renewalDate: "2025-08-08",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR013",
    name: "Anna Kendrick",
    type: "member",
    contact: "anna.k@example.com",
    plan: "Silver",
    renewalDate: "2025-07-16",
    role: "",
    status: "expired",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR014",
    name: "Leo Dsouza",
    type: "member",
    contact: "leo.d@example.com",
    plan: "Gold",
    renewalDate: "2025-08-14",
    role: "",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR015",
    name: "Ayesha Khan",
    type: "member",
    contact: "ayesha.k@example.com",
    plan: "Silver",
    renewalDate: "2025-07-29",
    role: "",
    status: "nearly renewal",
    checkInTime: "",
    method: "",
  },
  {
    id: "MBR016",
    name: "Steve Brown",
    type: "member",
    contact: "steve.b@example.com",
    plan: "Platinum",
    renewalDate: "2025-08-01",
    role: "",
    status: "active",
    checkInTime: "11:10 AM",
    method: "manual",
  },
  {
    id: "STF001",
    name: "Emily White",
    type: "staff",
    contact: "emily.white@example.com",
    plan: "",
    renewalDate: "",
    role: "Trainer",
    status: "active",
    checkInTime: "",
    method: "",
  },
  {
    id: "STF002",
    name: "Daniel Green",
    type: "staff",
    contact: "daniel.green@example.com",
    plan: "",
    renewalDate: "",
    role: "Manager",
    status: "active",
    checkInTime: "08:05 AM",
    method: "biometric",
  },
  {
    id: "STF003",
    name: "Meera Rao",
    type: "staff",
    contact: "meera.rao@example.com",
    plan: "",
    renewalDate: "",
    role: "Receptionist",
    status: "inactive",
    checkInTime: "",
    method: "",
  },
  {
    id: "STF004",
    name: "James Ford",
    type: "staff",
    contact: "james.ford@example.com",
    plan: "",
    renewalDate: "",
    role: "Cleaner",
    status: "active",
    checkInTime: "06:50 AM",
    method: "manual",
  },
];
